# Generated by Django 5.2.7 on 2025-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal_Species', models.CharField(max_length=200)),
                ('Animal_Name', models.CharField(max_length=200)),
                ('animal_Age', models.IntegerField(default=0)),
            ],
        ),
    ]
